
name.root.data   = projet-devappli

# Chemins des dossiers de regroupement
path.root.data   = ${path.root.appdata}/${name.root.data}
#path.root.data   = ${path.dir.current}/../${name.root.data}
path.root.backup = ${path.dir.current}/_backup

# Paramètres de Dbeaver
#args.dbeaver	 = -data "${path.root.data}/dbeaver/workspace6" 

# Durï¿½es d'attente (en millisecondes)
duration.refresh.status =  1500
duration.wait.starting  = 15000
duration.wait.stopping  = 10000

# Niveau de traces émises par ANT
# Valeurs possibles : ERR WARN INFO DEBUG VERBOSE
level.ant.logger = WARN
