-- Schema
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
-------
-- Tables

CREATE TABLE compte(
   id_compte BIGINT GENERATED BY DEFAULT AS IDENTITY,
   pseudo VARCHAR(25)  NOT NULL,
   email VARCHAR(50)  NOT NULL,
   empreinte_mdp VARCHAR(68)  NOT NULL,
   role_admin BOOLEAN NOT NULL DEFAULT FALSE,
   PRIMARY KEY(id_compte),
   UNIQUE(pseudo),
   UNIQUE(email)
);
